"""
Data loading and graph construction for GNN training.

Handles:
- Loading pre-computed embeddings from shap_data.pkl (from tcr_epitope_minimal.py)
- Building bipartite graphs
- Creating PyTorch Geometric datasets and loaders
"""

import logging
from pathlib import Path
from typing import Tuple, Optional
import pickle
import numpy as np
import pandas as pd
import torch
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader

logger = logging.getLogger(__name__)


class BipartiteGraphDataset:
    """
    Constructs a bipartite graph from TCR-Epitope pairs with pre-computed embeddings.
    
    Loads from shap_data.pkl generated by tcr_epitope_minimal.py
    
    Graph structure:
    - Node set 1: TCR sequences (with ESM2 embeddings)
    - Node set 2: Epitope sequences (with ESM2 embeddings)
    - Edges: TCR-Epitope binding pairs (labeled as positive/negative)
    """
    
    def __init__(
        self,
        shap_pkl_path: str,
        seed: int = 42,
    ):
        """
        Args:
            shap_pkl_path: Path to shap_data.pkl from tcr_epitope_minimal.py
            seed: Random seed
        """
        self.shap_pkl_path = shap_pkl_path
        self.seed = seed
        self.rng = np.random.default_rng(seed)
        
        logger.info(f"Loading data from {shap_pkl_path}")
        with open(shap_pkl_path, "rb") as f:
            self.data = pickle.load(f)
        
        self._prepare_data()
    
    def _prepare_data(self):
        """Extract embeddings and labels from pickle."""
        # Load concatenated embeddings
        self.X_test = self.data["X_test"]  # (N, 640) — TCR (320) + Epitope (320)
        self.X_tcr = self.data["X_test_tcr"]  # (N, 320)
        self.X_epi = self.data["X_test_epi"]  # (N, 320)
        self.y_test = self.data["y_test"]  # (N,) — 0 or 1
        self.df_meta = self.data.get("df_test_meta", pd.DataFrame())
        
        logger.info(f"X_test shape: {self.X_test.shape}")
        logger.info(f"X_tcr shape: {self.X_tcr.shape}")
        logger.info(f"X_epi shape: {self.X_epi.shape}")
        logger.info(f"y_test shape: {self.y_test.shape}")
        logger.info(f"Binding samples: {(self.y_test == 1).sum()}")
        logger.info(f"Non-binding samples: {(self.y_test == 0).sum()}")
    
    def build_graph(self) -> Data:
        """Build PyTorch Geometric graph from embeddings and labels."""
        logger.info("Building bipartite graph from embeddings...")
        
        n_samples = len(self.X_test)
        
        # Use concatenated embeddings as node features
        # Create a simple graph: each sample is an edge between a TCR node and Epitope node
        x = self.X_test  # (N, 640) — concatenated embeddings
        
        # Edge index: for each sample, create an edge (i, i) or (i, i+N/2)
        # Simpler: treat each sample as defining a TCR-Epitope pair
        # Node 0..N/2: TCRs, Node N/2..N: Epitopes
        # But since we don't have unique TCR/Epitope identity, create a simple line graph
        
        # Alternative: create edges as (sample_idx, sample_idx) with feature per sample
        # For link prediction, we need TCR and Epitope nodes separately
        # Since we don't have explicit TCR/Epitope node mappings, use a simple approach:
        # - Node i represents the i-th TCR-Epitope pair
        # - For link prediction, split embedding into TCR and Epitope halves
        
        num_nodes = n_samples
        x = torch.from_numpy(self.X_test).float()
        
        # Create edges between consecutive pairs (simple linear graph)
        edge_list = []
        for i in range(n_samples - 1):
            edge_list.append([i, i + 1])
        
        if not edge_list:
            # If only 1 sample, create self-loop
            edge_list = [[0, 0]]
        
        edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous()
        y = torch.from_numpy(self.y_test).long()
        
        logger.info(f"Graph: {num_nodes} nodes, {edge_index.shape[1]} edges")
        logger.info(f"Positive edges: {(y == 1).sum()}, Negative edges: {(y == 0).sum()}")
        
        graph = Data(
            x=x,
            edge_index=edge_index,
            y=y,
            num_nodes=num_nodes,
        )
        
        return graph
    
    def split_by_index(self, graph: Data, train_ratio: float = 0.8, val_ratio: float = 0.1):
        """Split graph by node indices for train/val/test."""
        n_samples = graph.num_nodes
        indices = self.rng.permutation(n_samples)
        
        train_end = int(n_samples * train_ratio)
        val_end = int(n_samples * (train_ratio + val_ratio))
        
        train_idx = set(indices[:train_end])
        val_idx = set(indices[train_end:val_end])
        test_idx = set(indices[val_end:])
        
        logger.info(f"Train nodes: {len(train_idx)}, Val: {len(val_idx)}, Test: {len(test_idx)}")
        
        def create_split_graph(idx_set):
            # Convert set to sorted list for consistent indexing
            idx_list = sorted(list(idx_set))
            idx_array = torch.tensor(idx_list, dtype=torch.long)
            
            # Get nodes in split
            node_mask = torch.tensor([i in idx_set for i in range(n_samples)], dtype=torch.bool)
            
            # Filter edges: only keep edges where both endpoints are in the split
            edge_mask = node_mask[graph.edge_index[0]] & node_mask[graph.edge_index[1]]
            filtered_edges = graph.edge_index[:, edge_mask]
            
            # Create mapping from old node indices to new indices
            old_to_new = {old_idx: new_idx for new_idx, old_idx in enumerate(idx_list)}
            
            # Remap edge indices
            remapped_edges = torch.zeros_like(filtered_edges)
            for i in range(filtered_edges.shape[0]):
                for j in range(filtered_edges.shape[1]):
                    remapped_edges[i, j] = old_to_new[filtered_edges[i, j].item()]
            
            split_graph = Data(
                x=graph.x[node_mask],
                edge_index=remapped_edges,
                y=graph.y[node_mask],
                num_nodes=len(idx_set),
            )
            return split_graph
        
        return create_split_graph(train_idx), create_split_graph(val_idx), create_split_graph(test_idx)


def create_data_loaders(
    shap_pkl_path: str = None,
    anndata_path: str = None,
    batch_size: int = 32,
    val_split: float = 0.2,
    test_split: float = 0.1,
    seed: int = 42,
) -> Tuple:
    """
    Create data loaders for train/val/test.
    
    Args:
        shap_pkl_path: Path to shap_data.pkl from tcr_epitope_minimal.py (preferred)
        anndata_path: Path to AnnData file (legacy, not used if shap_pkl_path provided)
        batch_size: Batch size for loaders
        val_split: Fraction of data for validation
        test_split: Fraction of data for test
        seed: Random seed
    
    Returns:
        (train_loader, val_loader, test_loader)
    """
    # Determine data source
    if shap_pkl_path is None and anndata_path is None:
        # Default to common output path
        shap_pkl_path = "outputs/outputs_v2/shap_data.pkl"
    
    if shap_pkl_path and Path(shap_pkl_path).exists():
        logger.info(f"Loading from shap_data.pkl: {shap_pkl_path}")
        dataset = BipartiteGraphDataset(shap_pkl_path, seed=seed)
    elif anndata_path and Path(anndata_path).exists():
        logger.info(f"Loading from AnnData: {anndata_path}")
        raise NotImplementedError("AnnData loading not yet implemented. Use shap_data.pkl instead.")
    else:
        raise FileNotFoundError(
            f"Could not find data files. Checked:\n"
            f"  - {shap_pkl_path or 'outputs/outputs_v2/shap_data.pkl'}\n"
            f"  - {anndata_path or 'not provided'}\n"
            f"Make sure tcr_epitope_minimal.py has been run first."
        )
    
    graph = dataset.build_graph()
    
    # Split by node index
    train_ratio = 1.0 - val_split - test_split
    train_graph, val_graph, test_graph = dataset.split_by_index(
        graph,
        train_ratio=train_ratio,
        val_ratio=val_split
    )
    
    # Create loaders
    train_loader = DataLoader([train_graph], batch_size=batch_size, shuffle=True)
    val_loader = DataLoader([val_graph], batch_size=batch_size, shuffle=False)
    test_loader = DataLoader([test_graph], batch_size=batch_size, shuffle=False)
    
    logger.info(f"Train nodes: {train_graph.num_nodes}, edges: {train_graph.edge_index.shape[1]}")
    logger.info(f"Val nodes: {val_graph.num_nodes}, edges: {val_graph.edge_index.shape[1]}")
    logger.info(f"Test nodes: {test_graph.num_nodes}, edges: {test_graph.edge_index.shape[1]}")
    
    return train_loader, val_loader, test_loader
