# this config is used to run iggytop with networkx as the dbms

biocypher:
  offline: true
  debug: true
  schema_config_path: config/schema_config.yaml
  dbms: networkx

neo4j:
  delimiter: '\t'
  array_delimiter: '|'
  quote_character: '"'
  skip_duplicate_nodes: true
  skip_bad_relationships: true
